  name: Debug env
  run: |
    echo CHAT_ID=%CHAT_ID%
    echo CHANNEL_CHAT_ID=%CHANNEL_CHAT_ID%
  env:
    BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
    CHAT_ID: ${{ secrets.CHAT_ID }}
    CHANNEL_CHAT_ID: ${{ secrets.CHANNEL_CHAT_ID }}

   name: Run scanner
  env:
    BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
    CHAT_ID: ${{ secrets.CHAT_ID }}
    CHANNEL_CHAT_ID: ${{ secrets.CHANNEL_CHAT_ID }}
  run: |
    python run.py
